<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageIcon>gw.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\..\..\..\VIR\gw.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.2" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.84.2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="_probe/**" />
  </ItemGroup>

</Project>